/* Fila 1 Asiento 3
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examenlab5p2_luiscastro;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author lfern
 */
public class Main extends javax.swing.JFrame {
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JF_empleado = new javax.swing.JFrame();
        pn_emp = new javax.swing.JPanel();
        lb_BienvenidoEmp = new javax.swing.JLabel();
        bttnexitemp = new javax.swing.JButton();
        tp_emp = new javax.swing.JTabbedPane();
        pn_InformacionC = new javax.swing.JPanel();
        lb_ICE = new javax.swing.JLabel();
        lb_TE = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_ice = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_te = new javax.swing.JTable();
        pn_Modificar = new javax.swing.JPanel();
        cb_modificar = new javax.swing.JComboBox<>();
        lb_nombreModificar = new javax.swing.JLabel();
        tf_nomMod = new javax.swing.JTextField();
        lb_sexo = new javax.swing.JLabel();
        tf_sexo = new javax.swing.JTextField();
        lb_apellido = new javax.swing.JLabel();
        tf_apellidoMod = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lb_contrasenia = new javax.swing.JLabel();
        tf_contraMod = new javax.swing.JTextField();
        tf_departamento = new javax.swing.JTextField();
        lb_fechaNac = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        pn_login = new javax.swing.JPanel();
        lb_InicioSesion = new javax.swing.JLabel();
        lb_nombreIS = new javax.swing.JLabel();
        lb_contraIS = new javax.swing.JLabel();
        bttnEntrar = new javax.swing.JButton();
        tf_nomIS = new javax.swing.JTextField();
        pf_contraIS = new javax.swing.JPasswordField();
        pn_exit = new javax.swing.JPanel();
        lb_exit = new javax.swing.JLabel();

        lb_BienvenidoEmp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_BienvenidoEmp.setText("Bienvenido!");

        bttnexitemp.setText("Cerrar Sesion");
        bttnexitemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnexitempActionPerformed(evt);
            }
        });

        lb_ICE.setText("Informacion Civiles:");

        lb_TE.setText("Tramites:");

        jt_ice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "No. Identidad", "Fecha Nacimiento"
            }
        ));
        jScrollPane1.setViewportView(jt_ice);

        jt_te.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre Tramite", "Descripcion", "Fecha", "No. Identidad"
            }
        ));
        jScrollPane2.setViewportView(jt_te);

        javax.swing.GroupLayout pn_InformacionCLayout = new javax.swing.GroupLayout(pn_InformacionC);
        pn_InformacionC.setLayout(pn_InformacionCLayout);
        pn_InformacionCLayout.setHorizontalGroup(
            pn_InformacionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_InformacionCLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pn_InformacionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_ICE, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_TE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_InformacionCLayout.setVerticalGroup(
            pn_InformacionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_InformacionCLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lb_ICE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lb_TE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
        );

        tp_emp.addTab("Informacion Civiles", pn_InformacionC);

        cb_modificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lb_nombreModificar.setText("Nombre");

        lb_sexo.setText("Sexo");

        lb_apellido.setText("Apellido");

        tf_apellidoMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_apellidoModActionPerformed(evt);
            }
        });

        jLabel4.setText("Departamento");

        lb_contrasenia.setText("Contrasenia");

        lb_fechaNac.setText("Fecha de nacimiento");

        javax.swing.GroupLayout pn_ModificarLayout = new javax.swing.GroupLayout(pn_Modificar);
        pn_Modificar.setLayout(pn_ModificarLayout);
        pn_ModificarLayout.setHorizontalGroup(
            pn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ModificarLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(cb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
            .addGroup(pn_ModificarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_ModificarLayout.createSequentialGroup()
                        .addGroup(pn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_nombreModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nomMod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_ModificarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addComponent(lb_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122))
                            .addGroup(pn_ModificarLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(tf_apellidoMod)
                                .addContainerGap())))
                    .addGroup(pn_ModificarLayout.createSequentialGroup()
                        .addGroup(pn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_contraMod)
                            .addComponent(lb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_sexo)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_departamento, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                        .addGap(64, 64, 64)
                        .addGroup(pn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_fechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pn_ModificarLayout.setVerticalGroup(
            pn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ModificarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(cb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(pn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombreModificar)
                    .addComponent(lb_apellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nomMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_apellidoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_contrasenia)
                    .addComponent(lb_fechaNac))
                .addGroup(pn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_ModificarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tf_contraMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_sexo)
                        .addGap(18, 18, 18)
                        .addComponent(tf_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_ModificarLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        tp_emp.addTab("Modificar Civiles", pn_Modificar);

        javax.swing.GroupLayout pn_empLayout = new javax.swing.GroupLayout(pn_emp);
        pn_emp.setLayout(pn_empLayout);
        pn_empLayout.setHorizontalGroup(
            pn_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_empLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pn_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_empLayout.createSequentialGroup()
                        .addComponent(tp_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addGroup(pn_empLayout.createSequentialGroup()
                        .addComponent(lb_BienvenidoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttnexitemp, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        pn_empLayout.setVerticalGroup(
            pn_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_empLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pn_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_BienvenidoEmp)
                    .addComponent(bttnexitemp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tp_emp)
                .addContainerGap())
        );

        javax.swing.GroupLayout JF_empleadoLayout = new javax.swing.GroupLayout(JF_empleado.getContentPane());
        JF_empleado.getContentPane().setLayout(JF_empleadoLayout);
        JF_empleadoLayout.setHorizontalGroup(
            JF_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_empleadoLayout.createSequentialGroup()
                .addComponent(pn_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JF_empleadoLayout.setVerticalGroup(
            JF_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_empleadoLayout.createSequentialGroup()
                .addComponent(pn_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JFrameMain");
        setUndecorated(true);

        lb_InicioSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_InicioSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_InicioSesion.setText("Inicio Sesion");

        lb_nombreIS.setText("Nombre completo");

        lb_contraIS.setText("Contraseña");

        bttnEntrar.setText("Entrar");
        bttnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttnEntrarMouseClicked(evt);
            }
        });

        pn_exit.setBackground(new java.awt.Color(255, 255, 255));
        pn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_exitMouseClicked(evt);
            }
        });

        lb_exit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_exit.setForeground(new java.awt.Color(0, 0, 0));
        lb_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_exit.setText("X");

        javax.swing.GroupLayout pn_exitLayout = new javax.swing.GroupLayout(pn_exit);
        pn_exit.setLayout(pn_exitLayout);
        pn_exitLayout.setHorizontalGroup(
            pn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_exitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_exitLayout.setVerticalGroup(
            pn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_exitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_loginLayout = new javax.swing.GroupLayout(pn_login);
        pn_login.setLayout(pn_loginLayout);
        pn_loginLayout.setHorizontalGroup(
            pn_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_loginLayout.createSequentialGroup()
                .addGroup(pn_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pf_contraIS, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bttnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pn_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_loginLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(lb_InicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_loginLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(pn_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_nombreIS, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_contraIS, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_nomIS, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(pn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        pn_loginLayout.setVerticalGroup(
            pn_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_loginLayout.createSequentialGroup()
                .addGroup(pn_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_loginLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lb_InicioSesion))
                    .addComponent(pn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(lb_nombreIS)
                .addGap(18, 18, 18)
                .addComponent(tf_nomIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lb_contraIS)
                .addGap(27, 27, 27)
                .addComponent(pf_contraIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(bttnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_pn_exitMouseClicked

    private void bttnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttnEntrarMouseClicked
        // TODO add your handling code here:
        if(tf_nomIS.getText().equals("Juana Ernesto")&& pf_contraIS.getText().equals("juanaernesto123")||tf_nomIS.getText().equals("Diego Rosales")&& pf_contraIS.getText().equals("drosales")){
            JOptionPane.showMessageDialog(this, "Ha entrado exitosamente.");
        }else{
            tf_nomIS.setText("");
            pf_contraIS.setText("");
            JOptionPane.showMessageDialog(this, "No se ha encontrado el usuario.");
        }
        if(tf_nomIS.getText().equals("Juana Ernesto")&& pf_contraIS.getText().equals("juanaernesto123")){
            this.setVisible(false);
            JF_empleado.pack();
            JF_empleado.setVisible(true);
        }
    }//GEN-LAST:event_bttnEntrarMouseClicked

    private void bttnexitempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnexitempActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        JF_empleado.setVisible(false);
        tf_nomIS.setText("");
        pf_contraIS.setText("");
    }//GEN-LAST:event_bttnexitempActionPerformed

    private void tf_apellidoModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_apellidoModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_apellidoModActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        ArrayList<usuarios> usuarios = new ArrayList();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date fecha = new Date(2005, 2, 31);
        Date fecha2 = new Date(1998, 8, 11);
        usuarios.add(new Empleados("Juana", "Ernesto", "juanaernesto123", fecha,"F", "Cortes"));
        usuarios.add(new Civiles("Diego", "Rosales", "drosales", fecha2, "M", "Comayagua"));
        String id1 = usuarios.get(0).generarID();
        String id2 = usuarios.get(1).generarID();
        usuarios.get(0).setIdentidad(id1);
        usuarios.get(1).setIdentidad(id2);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame JF_empleado;
    private javax.swing.JButton bttnEntrar;
    private javax.swing.JButton bttnexitemp;
    private javax.swing.JComboBox<String> cb_modificar;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jt_ice;
    private javax.swing.JTable jt_te;
    private javax.swing.JLabel lb_BienvenidoEmp;
    private javax.swing.JLabel lb_ICE;
    private javax.swing.JLabel lb_InicioSesion;
    private javax.swing.JLabel lb_TE;
    private javax.swing.JLabel lb_apellido;
    private javax.swing.JLabel lb_contraIS;
    private javax.swing.JLabel lb_contrasenia;
    private javax.swing.JLabel lb_exit;
    private javax.swing.JLabel lb_fechaNac;
    private javax.swing.JLabel lb_nombreIS;
    private javax.swing.JLabel lb_nombreModificar;
    private javax.swing.JLabel lb_sexo;
    private javax.swing.JPasswordField pf_contraIS;
    private javax.swing.JPanel pn_InformacionC;
    private javax.swing.JPanel pn_Modificar;
    private javax.swing.JPanel pn_emp;
    private javax.swing.JPanel pn_exit;
    private javax.swing.JPanel pn_login;
    private javax.swing.JTextField tf_apellidoMod;
    private javax.swing.JTextField tf_contraMod;
    private javax.swing.JTextField tf_departamento;
    private javax.swing.JTextField tf_nomIS;
    private javax.swing.JTextField tf_nomMod;
    private javax.swing.JTextField tf_sexo;
    private javax.swing.JTabbedPane tp_emp;
    // End of variables declaration//GEN-END:variables
}
