/* Fila 1 Asiento 3
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examenlab5p2_luiscastro;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lfern
 */
public class Main extends javax.swing.JFrame {
    
    /**
     * Creates new form Main
     */
    public Main() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date fecha = new Date(2005, 2, 31);
        Date fecha2 = new Date(1998, 8, 11);
        usuarios.add(new Empleados("Juana", "Ernesto", "juanaernesto123", fecha,"F", "Cortes"));
        usuarios.add(new Civiles("Diego", "Rosales", "drosales", fecha2, "M", "Comayagua"));
        String id1 = usuarios.get(0).generarID();
        String id2 = usuarios.get(1).generarID();
        usuarios.get(0).setIdentidad(id1);
        usuarios.get(1).setIdentidad(id2);
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JF_empleado = new javax.swing.JFrame();
        pn_emp = new javax.swing.JPanel();
        lb_BienvenidoEmp = new javax.swing.JLabel();
        bttnexitemp = new javax.swing.JButton();
        tp_emp = new javax.swing.JTabbedPane();
        pn_InformacionC = new javax.swing.JPanel();
        lb_ICE = new javax.swing.JLabel();
        lb_TE = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_ice = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_te = new javax.swing.JTable();
        pn_Modificar = new javax.swing.JPanel();
        cb_modificar = new javax.swing.JComboBox<>();
        lb_nombreModificar = new javax.swing.JLabel();
        tf_nomMod = new javax.swing.JTextField();
        lb_sexo = new javax.swing.JLabel();
        tf_sexo = new javax.swing.JTextField();
        lb_apellido = new javax.swing.JLabel();
        tf_apellidoMod = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lb_contrasenia = new javax.swing.JLabel();
        tf_contraMod = new javax.swing.JTextField();
        tf_departamento = new javax.swing.JTextField();
        lb_fechaNac = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        JF_civil = new javax.swing.JFrame();
        pn_civil = new javax.swing.JPanel();
        label_Bienvenido = new javax.swing.JLabel();
        bttnexitCivil = new javax.swing.JButton();
        jtp_civil = new javax.swing.JTabbedPane();
        pn_InPersonal = new javax.swing.JPanel();
        label_IP = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_infopersonal = new javax.swing.JTable();
        label_tramites = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_tramitespersonales = new javax.swing.JTable();
        pn_GestionTramites = new javax.swing.JPanel();
        label_DGT = new javax.swing.JLabel();
        tF_nombreGT = new javax.swing.JTextField();
        label_NGT = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tA_descripcion = new javax.swing.JTextArea();
        bttnEnviarTramites = new javax.swing.JButton();
        pn_login = new javax.swing.JPanel();
        lb_InicioSesion = new javax.swing.JLabel();
        lb_nombreIS = new javax.swing.JLabel();
        lb_contraIS = new javax.swing.JLabel();
        bttnEntrar = new javax.swing.JButton();
        tf_nomIS = new javax.swing.JTextField();
        pf_contraIS = new javax.swing.JPasswordField();
        pn_exit = new javax.swing.JPanel();
        lb_exit = new javax.swing.JLabel();

        JF_empleado.setUndecorated(true);

        lb_BienvenidoEmp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_BienvenidoEmp.setText("Bienvenido!");

        bttnexitemp.setText("Cerrar Sesion");
        bttnexitemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnexitempActionPerformed(evt);
            }
        });

        lb_ICE.setText("Informacion Civiles:");

        lb_TE.setText("Tramites:");

        jt_ice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "No. Identidad", "Fecha Nacimiento"
            }
        ));
        jScrollPane1.setViewportView(jt_ice);

        jt_te.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Tramite", "Descripcion", "Fecha", "No. Identidad"
            }
        ));
        jScrollPane2.setViewportView(jt_te);

        javax.swing.GroupLayout pn_InformacionCLayout = new javax.swing.GroupLayout(pn_InformacionC);
        pn_InformacionC.setLayout(pn_InformacionCLayout);
        pn_InformacionCLayout.setHorizontalGroup(
            pn_InformacionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_InformacionCLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pn_InformacionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_ICE, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_TE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_InformacionCLayout.setVerticalGroup(
            pn_InformacionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_InformacionCLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lb_ICE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lb_TE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
        );

        tp_emp.addTab("Informacion Civiles", pn_InformacionC);

        cb_modificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lb_nombreModificar.setText("Nombre");

        lb_sexo.setText("Sexo");

        lb_apellido.setText("Apellido");

        tf_apellidoMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_apellidoModActionPerformed(evt);
            }
        });

        jLabel4.setText("Departamento");

        lb_contrasenia.setText("Contrasenia");

        lb_fechaNac.setText("Fecha de nacimiento");

        javax.swing.GroupLayout pn_ModificarLayout = new javax.swing.GroupLayout(pn_Modificar);
        pn_Modificar.setLayout(pn_ModificarLayout);
        pn_ModificarLayout.setHorizontalGroup(
            pn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ModificarLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(cb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
            .addGroup(pn_ModificarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_ModificarLayout.createSequentialGroup()
                        .addGroup(pn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_nombreModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nomMod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_ModificarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addComponent(lb_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122))
                            .addGroup(pn_ModificarLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(tf_apellidoMod)
                                .addContainerGap())))
                    .addGroup(pn_ModificarLayout.createSequentialGroup()
                        .addGroup(pn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_contraMod)
                            .addComponent(lb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_sexo)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_departamento, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                        .addGap(64, 64, 64)
                        .addGroup(pn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_fechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pn_ModificarLayout.setVerticalGroup(
            pn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ModificarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(cb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(pn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombreModificar)
                    .addComponent(lb_apellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nomMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_apellidoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_contrasenia)
                    .addComponent(lb_fechaNac))
                .addGroup(pn_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_ModificarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tf_contraMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_sexo)
                        .addGap(18, 18, 18)
                        .addComponent(tf_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_ModificarLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        tp_emp.addTab("Modificar Civiles", pn_Modificar);

        javax.swing.GroupLayout pn_empLayout = new javax.swing.GroupLayout(pn_emp);
        pn_emp.setLayout(pn_empLayout);
        pn_empLayout.setHorizontalGroup(
            pn_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_empLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pn_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_empLayout.createSequentialGroup()
                        .addComponent(tp_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addGroup(pn_empLayout.createSequentialGroup()
                        .addComponent(lb_BienvenidoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttnexitemp, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        pn_empLayout.setVerticalGroup(
            pn_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_empLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pn_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_BienvenidoEmp)
                    .addComponent(bttnexitemp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tp_emp)
                .addContainerGap())
        );

        javax.swing.GroupLayout JF_empleadoLayout = new javax.swing.GroupLayout(JF_empleado.getContentPane());
        JF_empleado.getContentPane().setLayout(JF_empleadoLayout);
        JF_empleadoLayout.setHorizontalGroup(
            JF_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_empleadoLayout.createSequentialGroup()
                .addComponent(pn_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );
        JF_empleadoLayout.setVerticalGroup(
            JF_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_empleadoLayout.createSequentialGroup()
                .addComponent(pn_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );

        JF_civil.setUndecorated(true);

        label_Bienvenido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_Bienvenido.setText("Bienvenido!");

        bttnexitCivil.setText("Cerrar Sesion");
        bttnexitCivil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttnexitCivilMouseClicked(evt);
            }
        });
        bttnexitCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnexitCivilActionPerformed(evt);
            }
        });

        label_IP.setText("Informacion Personal:");

        jt_infopersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Completo", "No. Identidad", "Fecha Nacimiento"
            }
        ));
        jScrollPane3.setViewportView(jt_infopersonal);

        label_tramites.setText("Tramites:");

        jt_tramitespersonales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Tramite", "Descripcion", "Fecha", "No. Identidad"
            }
        ));
        jScrollPane4.setViewportView(jt_tramitespersonales);

        javax.swing.GroupLayout pn_InPersonalLayout = new javax.swing.GroupLayout(pn_InPersonal);
        pn_InPersonal.setLayout(pn_InPersonalLayout);
        pn_InPersonalLayout.setHorizontalGroup(
            pn_InPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_InPersonalLayout.createSequentialGroup()
                .addGroup(pn_InPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_InPersonalLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pn_InPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_IP, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_tramites, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pn_InPersonalLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pn_InPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_InPersonalLayout.setVerticalGroup(
            pn_InPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_InPersonalLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(label_IP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_tramites)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jtp_civil.addTab("Informacion Personal", pn_InPersonal);

        label_DGT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_DGT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_DGT.setText("Descripcion:");

        label_NGT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_NGT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_NGT.setText("Nombre:");

        tA_descripcion.setColumns(20);
        tA_descripcion.setRows(5);
        jScrollPane5.setViewportView(tA_descripcion);

        bttnEnviarTramites.setText("Enviar");
        bttnEnviarTramites.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttnEnviarTramitesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_GestionTramitesLayout = new javax.swing.GroupLayout(pn_GestionTramites);
        pn_GestionTramites.setLayout(pn_GestionTramitesLayout);
        pn_GestionTramitesLayout.setHorizontalGroup(
            pn_GestionTramitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_GestionTramitesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn_GestionTramitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                    .addComponent(tF_nombreGT))
                .addGap(28, 28, 28))
            .addGroup(pn_GestionTramitesLayout.createSequentialGroup()
                .addGroup(pn_GestionTramitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_GestionTramitesLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(label_DGT, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_GestionTramitesLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(label_NGT, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_GestionTramitesLayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(bttnEnviarTramites)))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        pn_GestionTramitesLayout.setVerticalGroup(
            pn_GestionTramitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_GestionTramitesLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(label_NGT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tF_nombreGT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_DGT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttnEnviarTramites)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jtp_civil.addTab("Gestion de Tramites", pn_GestionTramites);

        javax.swing.GroupLayout pn_civilLayout = new javax.swing.GroupLayout(pn_civil);
        pn_civil.setLayout(pn_civilLayout);
        pn_civilLayout.setHorizontalGroup(
            pn_civilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_civilLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(label_Bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttnexitCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addComponent(jtp_civil)
        );
        pn_civilLayout.setVerticalGroup(
            pn_civilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_civilLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pn_civilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bttnexitCivil, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(label_Bienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtp_civil))
        );

        javax.swing.GroupLayout JF_civilLayout = new javax.swing.GroupLayout(JF_civil.getContentPane());
        JF_civil.getContentPane().setLayout(JF_civilLayout);
        JF_civilLayout.setHorizontalGroup(
            JF_civilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_civil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JF_civilLayout.setVerticalGroup(
            JF_civilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_civil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JFrameMain");
        setUndecorated(true);
        setResizable(false);

        lb_InicioSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_InicioSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_InicioSesion.setText("Inicio Sesion");

        lb_nombreIS.setText("Nombre completo");

        lb_contraIS.setText("Contraseña");

        bttnEntrar.setText("Entrar");
        bttnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttnEntrarMouseClicked(evt);
            }
        });

        pn_exit.setBackground(new java.awt.Color(255, 255, 255));
        pn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_exitMouseClicked(evt);
            }
        });

        lb_exit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_exit.setForeground(new java.awt.Color(0, 0, 0));
        lb_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_exit.setText("X");

        javax.swing.GroupLayout pn_exitLayout = new javax.swing.GroupLayout(pn_exit);
        pn_exit.setLayout(pn_exitLayout);
        pn_exitLayout.setHorizontalGroup(
            pn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_exitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_exitLayout.setVerticalGroup(
            pn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_exitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_loginLayout = new javax.swing.GroupLayout(pn_login);
        pn_login.setLayout(pn_loginLayout);
        pn_loginLayout.setHorizontalGroup(
            pn_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_loginLayout.createSequentialGroup()
                .addGroup(pn_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pf_contraIS, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bttnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pn_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_loginLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(lb_InicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_loginLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(pn_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_nombreIS, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_contraIS, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_nomIS, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(pn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        pn_loginLayout.setVerticalGroup(
            pn_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_loginLayout.createSequentialGroup()
                .addGroup(pn_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_loginLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lb_InicioSesion))
                    .addComponent(pn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(lb_nombreIS)
                .addGap(18, 18, 18)
                .addComponent(tf_nomIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lb_contraIS)
                .addGap(27, 27, 27)
                .addComponent(pf_contraIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(bttnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_pn_exitMouseClicked

    private void bttnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttnEntrarMouseClicked
        // TODO add your handling code here:
        if(tf_nomIS.getText().equals(usuarios.get(0).getNombre()+" "+usuarios.get(0).getApellido())&& pf_contraIS.getText().equals(usuarios.get(0).getContra())||tf_nomIS.getText().equals(usuarios.get(1).getNombre()+" "+usuarios.get(1).getApellido())&& pf_contraIS.getText().equals(usuarios.get(1).getContra())){
            JOptionPane.showMessageDialog(this, "Ha entrado exitosamente.");
        }else{
            tf_nomIS.setText("");
            pf_contraIS.setText("");
            JOptionPane.showMessageDialog(this, "No se ha encontrado el usuario.");
        }
        if(tf_nomIS.getText().equals(usuarios.get(0).getNombre()+" "+usuarios.get(0).getApellido())&& pf_contraIS.getText().equals(usuarios.get(0).getContra())){
            
            this.setVisible(false);
            JF_empleado.pack();
            JF_empleado.setLocationRelativeTo(null);
            JF_empleado.setVisible(true);
            DefaultTableModel modelo = (DefaultTableModel)jt_ice.getModel();
            modelo.setRowCount(0);
            DefaultTableModel modelo1 = (DefaultTableModel)jt_te.getModel();
            modelo1.setRowCount(0);
            for (int i = 0; i< usuarios.size(); i++) {
               
                if(usuarios.get(i)instanceof Civiles){
                    Object [] filas = {
                        usuarios.get(i).getNombre()+" "+usuarios.get(i).getApellido(),
                        usuarios.get(i).getIdentidad(),
                        usuarios.get(i).getFecha_n()
                            
                    };
                    modelo.addRow(filas);
                    for(int j = 0; j < ((Civiles)usuarios.get(i)).tramites.size();j++){
                        Object [] filasT = {
                        ((Civiles)usuarios.get(j)).getTramites()
                        };
                        modelo1.addRow(filasT);
                    }
                    
                }
            }
        }else if(tf_nomIS.getText().equals(usuarios.get(1).getNombre()+" "+usuarios.get(1).getApellido())&& pf_contraIS.getText().equals(usuarios.get(1).getContra())){
            for(int i = 0; i < usuarios.size();i++){
                if((usuarios.get(i).getNombre()+" "+usuarios.get(i).getApellido()).equals(tf_nomIS.getText())){
                    index = usuarios.indexOf(usuarios.get(i));
                }
            }
            this.setVisible(false);
            String name = tf_nomIS.getText();
            JF_civil.pack();
            JF_civil.setLocationRelativeTo(null);
            JF_civil.setVisible(true);
            DefaultTableModel modelo = (DefaultTableModel) jt_infopersonal.getModel();
            modelo.setColumnCount(0);
            DefaultTableModel modelo1 = (DefaultTableModel) jt_tramitespersonales.getModel();
            modelo1.setColumnCount(0);
            
            for(int i = 0; i < usuarios.size();i++){
                if(usuarios.get(i)instanceof Civiles && (usuarios.get(i).getNombre()+" "+usuarios.get(i).getApellido()).equals(name)){
                    Object [] filas = {
                        usuarios.get(i).getNombre()+" "+usuarios.get(i).getApellido(),
                        usuarios.get(i).getIdentidad(),
                        usuarios.get(i).getFecha_n()
                    };
                    modelo.addRow(filas);    
                }
                if(usuarios.get(i)instanceof Civiles && (usuarios.get(i).getNombre()+" "+usuarios.get(i).getApellido()).equals(name)){
                    for(int j = 0; j < ((Civiles)usuarios.get(i)).tramites.size();j++){
                        Object [] filasT = {
                            ((Civiles)usuarios.get(i)).tramites.get(j)
                        };
                        modelo1.addRow(filasT);
                    }
                }
            }
        }
        
    }//GEN-LAST:event_bttnEntrarMouseClicked
    
    private void bttnexitempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnexitempActionPerformed
        // TODO add your handling code here:
        JF_empleado.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        tf_nomIS.setText("");
        pf_contraIS.setText("");
    }//GEN-LAST:event_bttnexitempActionPerformed

    private void tf_apellidoModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_apellidoModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_apellidoModActionPerformed

    private void bttnexitCivilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttnexitCivilMouseClicked
        // TODO add your handling code here:
        JF_civil.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        tf_nomIS.setText("");
        pf_contraIS.setText("");
    }//GEN-LAST:event_bttnexitCivilMouseClicked

    private void bttnexitCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnexitCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnexitCivilActionPerformed

    private void bttnEnviarTramitesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttnEnviarTramitesMouseClicked
        // TODO add your handling code here:
        String nombre = tF_nombreGT.getText();
        String descripcion = tA_descripcion.getText();
        String identidad = usuarios.get(index).getIdentidad();
        Date fecha = new Date();
       
        ((Civiles)usuarios.get(index)).tramites.add(new Tramites(nombre, descripcion, fecha, identidad));
    }//GEN-LAST:event_bttnEnviarTramitesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame JF_civil;
    private javax.swing.JFrame JF_empleado;
    private javax.swing.JButton bttnEntrar;
    private javax.swing.JButton bttnEnviarTramites;
    private javax.swing.JButton bttnexitCivil;
    private javax.swing.JButton bttnexitemp;
    private javax.swing.JComboBox<String> cb_modificar;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jt_ice;
    private javax.swing.JTable jt_infopersonal;
    private javax.swing.JTable jt_te;
    private javax.swing.JTable jt_tramitespersonales;
    private javax.swing.JTabbedPane jtp_civil;
    private javax.swing.JLabel label_Bienvenido;
    private javax.swing.JLabel label_DGT;
    private javax.swing.JLabel label_IP;
    private javax.swing.JLabel label_NGT;
    private javax.swing.JLabel label_tramites;
    private javax.swing.JLabel lb_BienvenidoEmp;
    private javax.swing.JLabel lb_ICE;
    private javax.swing.JLabel lb_InicioSesion;
    private javax.swing.JLabel lb_TE;
    private javax.swing.JLabel lb_apellido;
    private javax.swing.JLabel lb_contraIS;
    private javax.swing.JLabel lb_contrasenia;
    private javax.swing.JLabel lb_exit;
    private javax.swing.JLabel lb_fechaNac;
    private javax.swing.JLabel lb_nombreIS;
    private javax.swing.JLabel lb_nombreModificar;
    private javax.swing.JLabel lb_sexo;
    private javax.swing.JPasswordField pf_contraIS;
    private javax.swing.JPanel pn_GestionTramites;
    private javax.swing.JPanel pn_InPersonal;
    private javax.swing.JPanel pn_InformacionC;
    private javax.swing.JPanel pn_Modificar;
    private javax.swing.JPanel pn_civil;
    private javax.swing.JPanel pn_emp;
    private javax.swing.JPanel pn_exit;
    private javax.swing.JPanel pn_login;
    private javax.swing.JTextArea tA_descripcion;
    private javax.swing.JTextField tF_nombreGT;
    private javax.swing.JTextField tf_apellidoMod;
    private javax.swing.JTextField tf_contraMod;
    private javax.swing.JTextField tf_departamento;
    private javax.swing.JTextField tf_nomIS;
    private javax.swing.JTextField tf_nomMod;
    private javax.swing.JTextField tf_sexo;
    private javax.swing.JTabbedPane tp_emp;
    // End of variables declaration//GEN-END:variables
    public static ArrayList<usuarios>usuarios = new ArrayList();
    public static int index = 0;
}
